name: Feature
description: A feature this project should have
title: "[Feature] "
labels: [Enhancement]
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature
      description: Write about the feature here
    validations:
      required: true
  - type: textarea
    id: tasklist
    attributes:
      label: Task list
      description: What are the blocking issues or tasks needed in order to implement this?
      value: |
        - [ ] ...
        - [ ] Implement this feature
    validations:
      required: true
